### ISSUE TITLE
can you build linux arm64 package

### ISSUE THREAD

**Issue by CrazyJson** [kleisauke/libvips-packaging#3] opened 2020-07-07 14:25 UTC
Hello, using libvips picture processing package, found that the performance is very good;Currently, this package is required to be used on Linux ARM64. There is no official version of this package, and I tried to compile it myself but failed. Could you please help to compile a Linux ARM64 package

**Comment by kleisauke** [comment] 2020-07-08 12:50
The reason I didn't build for ARM64v8 (and ARMv7) was because I didn't have the necessary hardware to test it on. I also wasn't sure how much demand there is for this architecture. Nowadays these binaries can be tested on Travis and other CI providers. Commit https://github.com/kleisauke/libvips-packaging/commit/45b145f24d9dc21644660afdbb0a95a7cf774978 adds the build process for ARM64v8 and ARMv7.

Thanks for reporting this! This will be included in the forthcoming NetVips.Native release.

**Comment by kleisauke** [comment] 2020-07-13 17:27
A prerelease of [`NetVips.Native.linux-arm`](https://www.nuget.org/packages/NetVips.Native.linux-arm/8.10.0-beta2) and [`NetVips.Native.linux-arm64`](https://www.nuget.org/packages/NetVips.Native.linux-arm64/8.10.0-beta2) is now available.

**Comment by CrazyJson** [comment] 2020-07-14 03:01
Glad to hear that, update version to validate on ARM64 server immediately;But there was a little trouble;Error message prompt: Not found libvips.so.42;Detailed errors are as follows:
 "Unable to load shared library 'libvips.so.42' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibvips.so.42: cannot open shared object file: No such file or directory"

code example
![image](https://user-images.githubusercontent.com/8163485/87378873-76c1e500-c5c1-11ea-8701-4a629b4eca81.png)

**Comment by CrazyJson** [comment] 2020-07-14 03:03
[CANetLibvip.zip](https://github.com/kleisauke/libvips-packaging/files/4916296/CANetLibvip.zip)

**Comment by kleisauke** [comment] 2020-07-14 09:52
It looks like the wrong `RuntimeIdentifier` has been set during publishing in your example project, this should fix that:
```diff
--- a/Properties/PublishProfiles/FolderProfile.pubxml
+++ b/Properties/PublishProfiles/FolderProfile.pubxml
@@ -9,7 +9,7 @@ https://go.microsoft.com/fwlink/?LinkID=208121.
     <Platform>Any CPU</Platform>
     <TargetFramework>netcoreapp3.1</TargetFramework>
     <PublishDir>bin\Release\netcoreapp3.1\publish\</PublishDir>
-    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
+    <RuntimeIdentifier>linux-arm64</RuntimeIdentifier>
     <SelfContained>true</SelfContained>
     <PublishSingleFile>False</PublishSingleFile>
     <PublishReadyToRun>False</PublishReadyToRun>
```

Then just:
```bash
$ dotnet publish -p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml
```

To check if the correct shared library is published:
```bash
$ file bin/Release/netcoreapp3.1/publish/libvips.so.42
bin/Release/netcoreapp3.1/publish/libvips.so.42: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=e0816c99ebe766077d7ccdad074b77f8131f9e32, stripped
```

**Comment by CrazyJson** [comment] 2020-07-14 10:27
You can already find the libvips.so.42 file following your instructions, but you'll be reminded of the lack of new dependencies
`[root@arm-202 app]# dotnet CANetLibvip.dll
System.DllNotFoundException: Unable to load shared library 'libvips.so.42' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /lib64/liblibvips.so.42)
   at NetVips.Internal.Vips.GetFilename(Byte& vipsFilename)
   at NetVips.Image.NewFromFile(String vipsFilename, Nullable`1 memory, String access, Nullable`1 fail, VOption kwargs)
   at CANetLibvip.Program.Main(String[] args) in E:\xx\CANetLibvip\CANetLibvip\Program.cs:line 14
`

**Comment by kleisauke** [comment] 2020-07-14 11:41
Thanks for testing! It looks like the minimum required glibc (v2.29) is too high, making the ARM64 binaries incompatible on Linux distros shipped with older glibc versions.

Are you testing this on Ubuntu 18.04?

**Comment by kleisauke** [comment] 2020-07-17 13:51
Commit https://github.com/kleisauke/libvips-packaging/commit/72b47a7a79495b0350aab3c012bfe2d48f0cee10 reduces the minimum supported glibc version to 2.17 for the ARMv7 and ARM64v8 binaries. This is released as v8.10.0-rc1 on NuGet. The Travis ARM64 build on Ubuntu 18.04 now seems to run without any problems:
https://travis-ci.org/github/kleisauke/net-vips/jobs/709166978.

Let me know if this works for you!

**Comment by CrazyJson** [comment] 2020-07-18 15:19
I am glad that the program is working on ARM64. Thanks for your hard work

**Comment by kleisauke** [comment] 2020-08-26 15:06
[NetVips.Native.linux-arm v8.10.0](https://www.nuget.org/packages/NetVips.Native.linux-arm/8.10.0) and [NetVips.Native.linux-arm64 v8.10.0](https://www.nuget.org/packages/NetVips.Native.linux-arm64/8.10.0)   is now available. Thanks for testing!

**Comment by kleisauke** [comment] 2020-12-24 13:43
Re-opening as [NetVips.Native.linux-arm v8.10.5](https://www.nuget.org/packages/NetVips.Native.linux-arm/8.10.5) and [NetVips.Native.linux-arm64 v8.10.5](https://www.nuget.org/packages/NetVips.Native.linux-arm64/8.10.5) contains a regression, which was probably introduced in https://github.com/kleisauke/libvips-packaging/commit/9e3fbb731b058d32b61e5bff8098c2a2851320c2.
```bash
libvips.so.42: /usr/lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/.nuget/packages/netvips.native.linux-arm64/8.10.5/runtimes/linux-arm64/native/libvips.so.42)
```

Sorry that I didn't catch this earlier.

**Comment by kleisauke** [comment] 2020-12-27 15:00
The above regression was fixed with https://github.com/kleisauke/libvips-packaging/commit/2010b070968870bb6fbee716bbd8182fb1df859e and released as [NetVips.Native.linux-arm v8.10.5.1](https://www.nuget.org/packages/NetVips.Native.linux-arm/8.10.5.1) / [NetVips.Native.linux-arm64 v8.10.5.1](https://www.nuget.org/packages/NetVips.Native.linux-arm64/8.10.5.1) on NuGet.

**Closed as completed by kleisauke** 2020-12-27 15:00 UTC
Labels: enhancement
